//Javascript Created by Computerhope https://www.computerhope.com/
//store the quotations in arrays
var images = [],
index = 0;

images[0] = '<h2>"Shawshanki lunastus" (1994)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Shawhanki lunastus" class="center"><p>Neljakümnendad. Edukas pankur Andy (Tim Robbins) mõistetakse süüdi enda naise ning tolle armukese mõrvas. Ta saadetakse range reziimiga Shawshanki vanglasse, mille "põlised asukad" ei usu, et kidakeelne ning õbluke uustulnuk seal päevagi vastu peab. Kuid visa noormees ei loobu kergelt ning kohaneb ajapikku teiste vangide ning karmikäelise ülemusega. Tal on see ülioluline, mis teistel puudub - lootus ning unistused ...</p>';
images[1] = '<h2>"Ristiisa" (1972)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Ristiisa" class="center"><p>Kui kurikuulsa krimidünastia vananev juht "Don" Vito Corleone otsustab impeeriumi oma pojale pärandada ja narkoärisse sukelduda, tabab tema perekonda pingeline vastasseis teiste mõjuvõimsate maffiaperekondadega.</p>';
images[2] = '<h2>"Ristisa 2" (1974)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Ristisa 2" class="center"><p>Ristiisa II osa" jutustab noore Vito Corleone (Robert De Niro) karjääri algusaegadest. Vito kasvas üles 20. sajandi alguses Sitsiilias ja läks lõpuks New Yorki. Samuti on see ka lugu Vito pojast Michaelist (Al Pacino), kes juhib 1950ndatel perekonna äri, üritades oma haaret laiendada ka Las Vegases ja Kuubas.</p>';
images[3] = '<h2>"Pimeduse rüütel" (2008)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Pimeduse rüütel" class="center"><p>Batman (Christian Bale) püüab puhastada Gotham City organiseeritud kuritegevusest. Selle ülesande lahendamisel aitavad teda leitnant Jim Gordon (Gary Oldman) ja prokurör Harvey Dent (Aaron Eckhart). Kolmik on oma töös väga edukas, kuni saab vastaseks uue superkurjategija, keda tuntakse nimel all Jokker (Heath Ledger). Viimane paiskab kogu Gothami anarhia küüsi, sundides Batmani sammhaaval lähemale piirile, mis lahutab kangelaslikkust omakohtust.</p>';
images[4] = '<h2>"12 vihast meest" (1957)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="12 vihast meest" class="center"><p>Nooruk Puerto Ricost on pandud kohtu alla süüdistatuna oma isa pussitamises. 12 vandekohtunikku peavad otsustama ühe noore inimese saatuse üle. Olgugi, et ei tundu olevat mitte mingit kahtlust, et kohtualune on süüdi, kahtleb vaid üks kaheteistkümnest vandekohtunikust noormehe süüs. Kuna otsus peab olema ühene, algab vandekohtunike ruumis pingeline arutelu. Henry Fonda kehastab kaheksandat vandekohtunikku, kes ainsana pole veendunud noormere süüs.</p>';
images[5] = '<h2>"Schindleri nimekiri" (1993)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Schindleri nimekiri" class="center"><p>Tõestisündinud lool põhinev film, mis räägib Oskar Schindleri, ahne ja jõuka saksa ärimehe, tegudest Teise maailmasõja vältel. Ta suutis päästa üle 1100 juudi surmast gaasikambris ja märkis nad kõik üles enda koostatud nimekirja.</p>';
images[6] = '<h2>"Sõrmuste isand: Kuninga tagasitulek" (2004)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Sõrmuste isand: Kuninga tagasitulek" class="center"><p>Sauroni väed ründavad Gondori pealinna Minas Tirith\'it. Kunagine võimas kuningriik pole iial vajanud endale rohkem kindlakäelist valitsejat. Aga kas Aragorn (Viggo Mortensen) leiab endas jõudu, et võtta vastu oma saatus? Gandalf (Ian McKellen) püüab koondada vägesid, kuningas Théoden (Bernard Hill) toob appi Rohani võitlejad. Aga inimeste vägedest ei ole väärilist vastast tohututele vaenalse hordidele. Siiski tormavad nad võitlusesse, et tõmmata endale Sauroni tähelepanu, sest ainult nii on Frodol (Elijah Wood) lootust täita oma tohutult raske ülesanne.</p>';
images[7] = '<h2>"Pulp fiction" (1994)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Pulp fiction" class="center"><p>Kaks palgamõrvarit Vincent Vega (John Travolta) ja Jules Winnfield (Samuel L. Jackson) on missioonil leidmaks salapärast kohvrit, mis kuulub nende bossile Marsellus Wallace`ile (Ving Rhames). Olles end Wallace`i silmis kenasti tõestanud, saab Vincent endale uue ülesande: hoolitseda bossi naise Mia (Uma Thurman) eest kui Wallace ise on tööasjadega parasjagu hõivatud. Samal ajal on Wallace maksnud kinni poksimatši, et vananev poksija Butch Coolidge (Bruce Willis) kaotaks meelega oma järgmise võitluse. Loomulikult ei kulge kõik nii nagu planeeritud. Kõikide nende väga meelelahutuslike tegelaste elud põimuvad väga ootamatul ja vägivaldsel viisil. </p>';
images[8] = '<h2>"Hea, halb ja inetu" (1964)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Hea, halb ja inetu" class="center"><p>Kaks relvavenda sõlmivad kokkuleppe. Üks neist (Eli Wallach) on tagaotsitav, kelle eest on välja pandud suur autasu. Kokkuleppe järgi annab teine (Clint Eastwood) tagaotsitava üles, saab selle eest vastavalt tasutud ning poomishetkel vabastab tolle. Hiljem teevad nad saagi pooleks. Kuid siiski lõpetavad nad hoopis mõlemad vanglas. Kuid neil on ka saladus - nad teavad, kuhu on peidetud kodusõja ajal suur hulk tööliste palgaraha. Vanglas saab nende teadmistest haisu ninna vanglaülem (Lee Van Cleef), kes ka ise seda endale tahaks. Nüüd ta ajabki vangid jalule ning need kolm lähevad koos seda raha otsima ...</p>';
images[9] = '<h2>"Kaklusklubi" (1999)</h2><img src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3290/3290236_sa.jpg" alt="Kaklusklubi" class="center"><p>Sa ei ole oma töökoht. Sa ei ole oma pangaarve. Sa ei ole oma rahakoti sisu. Sa ei ole oma ülikond. See on su elu ja see lõpeb minutihaaval. Kõigepealt ei saa sa magada, järgmisel hetkel leiad end püstolitoru suhu pistetud. Järgmiseks kohtad Tyler Durdenit. Tyler ütleb, et asjad, mida sa omad, saavad lõpuks hoopis sinu omanikuks. Alles siis, kui sa oled kõigest ilma jäänud, oled vaba tegema ükskõik mida. Kaklusklubi esindab just sellist vabadust. Kaklusklubi esimene reegel: Kaklusklubist ei räägita. Kaklusklubi teine reegel: Kaklusklubist ei räägita...</p>';

index = Math.floor(Math.random() * images.length);
document.write(images[index]);
//done